language: php

php:
  - 5.5.9

before_script:
  - cd app
  - composer self-update
  - composer install

script:
  - cd ..
  - ./bin/test

after_script:
  - php vendor/bin/coveralls

branches:
  only:
    - master
    - develop
