#!/bin/bash

set -eux

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# This script assumes that it lives two directories below the base directory.
BASE_DIR="$( cd $MY_DIR/../.. && pwd )"

pushd ${BASE_DIR}
  bundle
  bundle exec middleman build --clean

  cp source/resume/robdimsdale-resume.html build/resume/robdimsdale-resume.html
popd
