#!/bin/bash

set -eux

my_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# This script assumes that it lives two directories below the base directory.
base_dir="$( cd "${my_dir}/../.." && pwd )"

CF_API="${CF_API:-https://api.run.pivotal.io}"
CF_ORG=${CF_ORG:?}
CF_SPACE=${CF_SPACE:?}
CF_USER=${CF_USER:?}
CF_APPLICATION=${CF_APPLICATION:?}

cf api "${CF_API}"

set +x
CF_PASSWORD=${CF_PASSWORD:?}
cf auth "${CF_USER}" "${CF_PASSWORD}"
set -x

cf target \
  -o "${CF_ORG}" \
  -s "${CF_SPACE}"

pushd "${base_dir}"
  # Do not leak credentials
  set +x

  STATIC_FILE_AUTH=${STATIC_FILE_AUTH:-}
  if [ "${STATIC_FILE_AUTH}" != "" ]; then
    echo "\$STATIC_FILE_AUTH detected - writing to Staticfile.auth"
    echo "${STATIC_FILE_AUTH}" > Staticfile.auth
  fi

  cf push "${CF_APPLICATION}" \
    -m 64M \
    -b https://github.com/cloudfoundry/staticfile-buildpack.git \
    | grep -v "${STATIC_FILE_AUTH}"
popd
