---
resources:
- name: website-develop
  type: git
  source:
    uri: git@github.com:robdimsdale/dimsdale-website
    branch: develop
    private_key: {{private-key}}

- name: website-master
  type: git
  source:
    uri: git@github.com:robdimsdale/dimsdale-website
    branch: master
    private_key: {{private-key}}

- name: slack_alert
  type: slack-notification
  source:
    url: {{slack-url}}

jobs:
- name: build-deploy-site-develop
  serial: true
  plan:
  - get: website-develop
    trigger: true
  - task: build-deploy-site-develop
    file: website-develop/scripts/ci/build_deploy_site_develop.yml
    config:
      params:
        CF_USER: {{cf-user}}
        CF_PASSWORD: {{cf-password}}
        CF_ORG: {{cf-org-develop}}
        CF_SPACE: {{cf-space-develop}}
        CF_APPLICATION: {{cf-application-develop}}
        STATIC_FILE_AUTH: {{static-file-auth-develop}}
    on_success:
      put: slack_alert
      params:
        username: concourse
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        channel: {{slack-channel}}
        text: {{slack-develop-success-text}}
    on_failure:
      put: slack_alert
      params:
        username: concourse
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        channel: {{slack-channel}}
        text: {{slack-develop-failure-text}}

- name: build-deploy-site-master
  serial: true
  plan:
  - get: website-master
    trigger: true
  - task: build-deploy-site-master
    file: website-master/scripts/ci/build_deploy_site_master.yml
    config:
      params:
        CF_USER: {{cf-user}}
        CF_PASSWORD: {{cf-password}}
        CF_ORG: {{cf-org-master}}
        CF_SPACE: {{cf-space-master}}
        CF_APPLICATION: {{cf-application-master}}
    on_success:
      put: slack_alert
      params:
        username: concourse
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        channel: {{slack-channel}}
        text: {{slack-master-success-text}}
    on_failure:
      put: slack_alert
      params:
        username: concourse
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        channel: {{slack-channel}}
        text: {{slack-master-failure-text}}
