#!/bin/bash

set -eux

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# This script assumes that it lives one directory below the base directory.
BASE_DIR="$( cd $MY_DIR/.. && pwd )"

JSON_DIR="${BASE_DIR}/resume-json"
HTML_DIR="${BASE_DIR}/source/resume"
RESUME_THEME=classy

RESUME_VERSION=$(resume --version)
echo "Using resume-cli version: ${RESUME_VERSION}"
echo "Using theme: ${RESUME_THEME}"

pushd "${JSON_DIR}"
  resume export resume.json --theme "${RESUME_THEME}" --format html
popd

cp "${JSON_DIR}/resume.json" "${HTML_DIR}/robdimsdale-resume.json"
cp "${JSON_DIR}/resume.html" "${HTML_DIR}/robdimsdale-resume.html"
